[WIP] feat: (platform) table - phase 1
valor-software/fundamental-ngx pull request #56
Opened 2020-09-23 08:36 UTC by olshansky

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3252
#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-10-08 16:08 UTC, Betrozov requested changes

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/table.component.html
> +        <ng-container *ngTemplateOutlet="tableToolbarComponent.contentTemplateRef; context: { counter: rows.length || 0, size: contentDensity }"></ng-container>
in what cases it be work `|| 0`?

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/table.component.html
> +                    [tabIndex]="selectionMode === 'single' ? 0 : -1"
plz use enum for 'single' and 'multiple'

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/table.component.html
> +    <div>{{ emptyTableMessage }}</div>
[innerText]?

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/types/column-align.type.ts
> +export type ColumnAlign = 'start' | 'end' | 'center';
why not use enum for it?

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/types/content-density.type.ts
> +export type ContentDensity = 'compact' | 'cozy' | 'condensed';
the same

2020-10-08 16:08 UTC, Betrozov commented on libs/platform/src/lib/components/table/types/selection-mode.type.ts
> +export type SelectionMode = 'single' | 'multiple' | 'none';
the same

2020-10-09 07:36 UTC, olshansky commented on libs/platform/src/lib/components/table/table.component.html
> +    <div>{{ emptyTableMessage }}</div>
`emptyTableMessage ` will come from outside. I'm not sure that developers will provide a pure string _(as I remember `innerText` skip sanitizing and put all from the variable to the block text)_
@Betrozov so, should I put it to `innerText`, what do you think?

2020-10-09 10:36 UTC, Betrozov commented on libs/platform/src/lib/components/table/table.component.html
> +    <div>{{ emptyTableMessage }}</div>
will add sanitizing or use innerText
choose at your discretion

2020-10-21 07:21 UTC, olshansky commented
Merged https://github.com/SAP/fundamental-ngx/pull/3597

2020-10-21 07:21 UTC, closed without merging