[WIP] feat: (core) introduce object number component
valor-software/fundamental-ngx pull request #65
Opened 2020-09-30 13:05 UTC by IlyaSurmay

#### Please provide a link to the associated issue.

https://github.com/SAP/fundamental-ngx/issues/3284

#### Please provide a brief summary of this pull request.

Introduce core object number component

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-09-30 14:06 UTC, EvilAlexei approved these changes

2020-09-30 14:53 UTC, dimamarksman requested changes

2020-09-30 14:53 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.spec.ts
> +        component.onChanges();
is there any special meaning to call `onChanges` taking into account that `fixture.detectChanges();` gets called as well?

2020-09-30 14:53 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.ts
> +    numberPipeConfig = '';
since it belongs to private API it should have `_` prefix.

2020-09-30 14:53 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.ts
> +    ariaLabelledBy: string = null;
What is the reason to have such kind of binding without default value?
The host element is exposed to app developer so he is able to assign any attribute he wants.

2020-09-30 16:26 UTC, IlyaSurmay commented on libs/core/src/lib/object-number/object-number.component.ts
> +    ariaLabelledBy: string = null;
default value won't make any sense here because only developer will know which element is used as a label

2020-09-30 16:27 UTC, IlyaSurmay commented on libs/core/src/lib/object-number/object-number.component.spec.ts
> +        component.onChanges();
you're right, it's useless here, I removed these calls

2020-09-30 16:28 UTC, EvilAlexei commented on libs/core/src/lib/object-number/object-number.component.ts
> +    numberPipeConfig = '';
It's kinda strange because it's not "private".
I think you should use `_` prefix when it's really private, otherwise, it's confusing.
```
private _numberPipeConfig = '';
```

2020-09-30 16:32 UTC, IlyaSurmay commented on libs/core/src/lib/object-number/object-number.component.ts
> +    numberPipeConfig = '';
make sense to me, it's used in the template so there's no way to make it truly private, this prefix is just for developer's convenience

2020-09-30 16:40 UTC, EvilAlexei commented on libs/core/src/lib/object-number/object-number.component.ts
> +    numberPipeConfig = '';
And that's the case, it will be not truly private, so what's the reason say so?
For me, things should be called for what they are, but not for what they should look like.

Anyway, it's all about project agreements and if it's a common practice here - why not.
But in my opinion, it's a bad practice

2020-10-01 07:44 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.ts
> +    ariaLabelledBy: string = null;
Agree with it, intended to highlight the `ariaLabel` line but accidentally highlighted this one :)
Anyway what is a reson to have this kind of binding?
For example app developer wants to add aria-label, in this case he is able just add it by assigning this attribute directly to the host element:
```
<fd-object-number [number]="100" aria-label="My super number"></fd-object-number>
```
The same should be true for `class` binding as well. Even without `@Input() class` we should be able do the next:
```
<fd-object-number [number]="100" class="my-custom-class-1 my-custom-class-2"></fd-object-number>
```

2020-10-01 07:49 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.ts
> +    numberPipeConfig = '';
That's the common practice here.
This prefix gives a hint to a developer that this property should be considered as private and should not be touched outside of the component.

2020-10-01 08:54 UTC, IlyaSurmay commented on libs/core/src/lib/object-number/object-number.component.ts
> +    ariaLabelledBy: string = null;
I agree, these inputs look redundant. `class` is a required property to have if a component implements `CssClassBuilder` (which is needed for `buildComponentCssClass()`)
It is also true for aria attributes but it seems to be a common practice in this project because specs explicitly say that components should have them and a lot of existing components have them (alert, message strip, busy indicator)

2020-10-01 09:12 UTC, dimamarksman commented on libs/core/src/lib/object-number/object-number.component.ts
> +    ariaLabelledBy: string = null;
Yeah, there are a lot of places in the project with the same stuff, but from my point of view it's redundent and doesn't make sense, it brings extra bindings without any real value.

2020-10-01 09:20 UTC, dimamarksman approved these changes
LGTM

2020-10-06 16:52 UTC, fkolar approved these changes

2020-10-07 12:24 UTC, closed without merging