Feat/formatted text
valor-software/fundamental-ngx pull request #72
Opened 2020-10-05 18:04 UTC by mykolavorobiov

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-10-06 10:58 UTC, fkolar requested changes
Looks good. just minor things

2020-10-06 10:58 UTC, fkolar commented on libs/core/src/lib/formatted-text/formatted-text.component.ts
> +    @HostBinding('class.fd-formatted-text-with-height')
We should probably keep some uniformity in formatting. 
either havel inlined decorators -> property or each on new line.

2020-10-06 10:58 UTC, fkolar commented on libs/core/src/lib/formatted-text/utils/html-sanitizer.ts
> +
Is this custom made written from the scratch or you get inspired by some project? If we have some similar pieces, we need to add attribution, just in case.. and licence

2020-10-06 11:08 UTC, IlyaSurmay commented on apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.component.html
> +<fd-docs-section-title [id]="'default'" [componentName]="'formatted-text'">
how about changing this from property to attribute bindings?
`<fd-docs-section-title id="default" componentName="formatted-text">`

2020-10-06 11:08 UTC, IlyaSurmay commented on apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.module.ts
> +import { FormattedTextModule } from '@fundamental-ngx/core';
please move this to lib imports

2020-10-06 11:08 UTC, IlyaSurmay commented on libs/core/src/lib/formatted-text/utils/html-sanitizer.ts
> +    private makeSanitizedCopy(node: any): HTMLElement {
`node: HTMLElement`?

2020-10-06 11:44 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.module.ts
> +import { FormattedTextModule } from '@fundamental-ngx/core';
Rearranged

2020-10-06 12:30 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.component.html
> +<fd-docs-section-title [id]="'default'" [componentName]="'formatted-text'">
Updated

2020-10-06 12:50 UTC, mykolavorobiov commented on libs/core/src/lib/formatted-text/formatted-text.component.ts
> +    @HostBinding('class.fd-formatted-text-with-height')
Fixed

2020-10-06 13:32 UTC, mykolavorobiov commented on libs/core/src/lib/formatted-text/utils/html-sanitizer.ts
> +
I was inspired by these projects

[sanitize-html](https://www.npmjs.com/package/sanitize-html)
[dompurify](https://www.npmjs.com/package/dompurify)

but I don’t use anything from them. Sure thing, I have found pieces of similar code in few posts, but it doesn’t depend on any library and is not covered by any license.

p.s. I think that [sanitize-html](https://www.npmjs.com/package/sanitize-html) is the best solution to append user embed code safely.
But I'm not sure, if we need more code than it is in my version.
We don't need to control script and form in embed code, we will skip it. As for me, I think that the manual sandbox's iframe is the easiest way.

2020-10-06 13:32 UTC, mykolavorobiov commented on libs/core/src/lib/formatted-text/utils/html-sanitizer.ts
> +    private makeSanitizedCopy(node: any): HTMLElement {
I added interfaces.
p.s.
HTMLElement extends Element, Element extends Node, but from HTMLElement we have no access to Node methods. Could you please, let me know if you have much better solution in this case than 'as'?

2020-10-06 16:51 UTC, fkolar approved these changes

2020-10-07 08:38 UTC, IlyaSurmay approved these changes

2020-10-07 12:51 UTC, closed without merging

2020-10-07 12:52 UTC, mykolavorobiov commented
Open the same PR to the SAP repository