feat: (Core) introduce Rating Indicator
valor-software/fundamental-ngx pull request #88
Opened 2020-10-21 11:41 UTC by mykolavorobiov

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3037

#### Please provide a brief summary of this pull request.
Introduce Rating Indicator component to fundumental-ngx core

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-10-21 12:03 UTC, IlyaSurmay requested changes

2020-10-21 12:03 UTC, IlyaSurmay commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +            (<a href="javascript:;" fd-link>{{ totalRatings }}</a>)
does this needs to be an `a` element?

2020-10-21 12:03 UTC, IlyaSurmay commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +        #ttt
tttttratata
please change the name to something meaningful

2020-10-21 12:03 UTC, IlyaSurmay commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.spec.ts
> +// import { PopoverComponent } from '../../popover/popover.component';
please remove this

2020-10-21 12:03 UTC, IlyaSurmay commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +        if ('size' in changes) {
can be combined with `if ('class' in changes)`

2020-10-21 13:06 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +            (<a href="javascript:;" fd-link>{{ totalRatings }}</a>)
Only for the correct view. It will show that you can hover this element (and you will see popover).

2020-10-21 13:11 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +        if ('size' in changes) {
Moved

2020-10-21 13:11 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.spec.ts
> +// import { PopoverComponent } from '../../popover/popover.component';
Removed

2020-10-21 13:12 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +        #ttt
Removed, it's unnecessary

2020-10-21 13:12 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs.module.ts
> +import { RatingIndicatorModule, ShellbarModule } from '@fundamental-ngx/core';
Moved

2020-10-21 13:12 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-ratings.component.ts
> +import { RatingIndicatorOutput } from '@fundamental-ngx/core';
Removed

2020-10-21 13:12 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-ratings.component.ts
> +const config = {
Removed

2020-10-21 13:12 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-base.component.html
> +<div style="display: flex; align-items: flex-start; justify-content: flex-start; flex-direction: column; border-bottom: 1px solid grey;; padding-bottom: 0.5rem; margin-bottom: 0.5rem">
Moved to separate style file

2020-10-21 13:12 UTC, mykolavorobiov commented on README.md
> -[![REUSE status](https://api.reuse.software/badge/github.com/SAP/fundamental-ngx)](https://api.reuse.software/info/github.com/SAP/fundamental-ngx)
Restored

2020-10-21 14:26 UTC, IlyaSurmay approved these changes

2020-10-23 12:33 UTC, dimamarksman requested changes
Looks good,
please see my comments

2020-10-23 12:33 UTC, dimamarksman commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +            this._elementRef.nativeElement.style.setProperty('custom-indicator-icon-rated', `${this.ratedIcon}`);
Also could you please explain what is the purpose if this assign?
This code looks like invalid one.

2020-10-23 12:33 UTC, dimamarksman commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +                if (+key < INDICATOR_RANGE.min || +key > INDICATOR_RANGE.max) {
let's do `+key` only once in the beginning.

2020-10-23 12:33 UTC, dimamarksman commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    ratingChanged = new EventEmitter<RatingIndicatorOutput>();
According to [the spec](https://app.gitbook.com/@fundamental-ngx/s/docs/approved/core-rating-indicator) payload should be just a number.
Is there any advantage keeping it as an object?

2020-10-27 08:15 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    ratingChanged = new EventEmitter<RatingIndicatorOutput>();
Okay, will change.
But as the best way - output should return object because you can change or modify some fields easily. Maybe this case is not really the best example but in general, it would be better.

2020-10-27 08:15 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +                if (+key < INDICATOR_RANGE.min || +key > INDICATOR_RANGE.max) {
Okay, will change.

2020-10-27 08:16 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    icons: { id: string; value: number }[] = [];
Okay, will change.

2020-10-27 08:16 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    private ratingUID = 0;
Okay, will change.

2020-10-27 08:16 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.scss
> +  .zero-rating {
It's a private class, do we really need to use BEM in this case?

2020-10-27 08:17 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.scss
> +  .zero-rating {
Okay, will change

2020-10-27 08:17 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +    <span *ngIf="!totalRatings" class="fd-rating-indicator__dynamic-text">({{ viewValue }} of {{ indicatorCount }})</span>
Okay, will change

2020-10-27 08:17 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-sizes.component.html
> +        <div style="display: flex; align-items: flex-start; justify-content: flex-start; flex-direction: column;">
Okay, will change

2020-10-27 12:26 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
> +                        <i *ngIf="unratedIcon" class="unrated" [ngClass]="ratedIcon"></i>
Okay, will remove

2020-10-27 13:27 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-example.component.html
> +            <option [value]=size *ngFor="let size of sizes; trackBy: trackByFn">{{ size }}</option>
Okay, will remove

2020-10-27 13:28 UTC, mykolavorobiov commented on apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-base.component.ts
> +    }
It's unnecessary, will remove.

2020-10-27 13:35 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +            this._elementRef.nativeElement.style.setProperty('custom-indicator-icon-rated', `${this.ratedIcon}`);
Will remove the unnecessary wrapping.
Will remove the unnecessary assignments.
All logic will cover in the template.

2020-10-27 13:41 UTC, mykolavorobiov commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    private ratingUID = 0;
About assignment - nope, we couldn't.

2020-10-27 13:52 UTC, dimamarksman commented on libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
> +    private ratingUID = 0;
Could you please explain why we can't do that.

2020-10-27 14:44 UTC, dimamarksman approved these changes
LGTM

2020-10-27 17:34 UTC, closed without merging

2020-10-27 17:35 UTC, mykolavorobiov commented
Moved to new PR into SAP repository