fix: (platform) upload collection
valor-software/fundamental-ngx pull request #95
Opened 2020-10-27 09:04 UTC by Betrozov

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3171
#### Please provide a brief summary of this pull request.
Introduce new Platform Upload Collection component
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-10-27 14:09 UTC, IlyaSurmay requested changes

2020-10-27 14:09 UTC, IlyaSurmay commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
> +import { take } from 'rxjs/operators';
please move this up to lib imports

2020-10-27 14:09 UTC, IlyaSurmay commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
> +                console.log(error);
maybe `console.error(error)` is more suitable here?

2020-10-27 15:06 UTC, Betrozov commented on apps/docs/src/app/platform/component-docs/upload-collection/upload-collection-header/upload-collection-header.component.ts
> +  constructor() { }
fixed

2020-10-27 15:06 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.html
> +    <fd-dialog-body style="padding-left: 0; padding-right: 0">
fixed

2020-10-27 15:06 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/directives/upload-collection-dragndrop.directive.ts
> +    // .fdp-upload-collection__table
removed

2020-10-27 15:06 UTC, Betrozov commented on package.json
> +    "start": "node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng serve",
reverted

2020-10-27 15:07 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
> +import { take } from 'rxjs/operators';
sorted

2020-10-27 15:07 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
> +                console.log(error);
changed

2020-10-27 15:14 UTC, IlyaSurmay approved these changes

2020-10-27 16:33 UTC, Betrozov commented on apps/docs/src/app/platform/component-docs/upload-collection/examples/upload-collection-base.service.ts
> +        console.log('upload', data);
This is just an example of how to work with `UploadCollectionService`.
All the consoles need here to see the result in the browser console

2020-10-27 16:36 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.spec.ts
> +});
unit tests will be tomorrow

2020-10-27 16:36 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.html
> +                (click)="this.dialogRef.close(newFolderName)"
fixed

2020-10-27 16:36 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.html
> +                (click)="this.dialogRef.dismiss()"
fixed

2020-10-27 16:36 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.html
> +                (click)="dialogRef.dismiss()"
fixed

2020-10-27 16:37 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.html
> +                (click)="dialogRef.dismiss()"
fixed

2020-10-27 18:11 UTC, olshansky commented on package.json
> +    "start": "node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng serve",
@Betrozov it's still here 🤔

2020-10-27 20:50 UTC, fkolar commented
My Major comment would be that `Upload Collection `should be part of the Inputs. Upload components are usually used as part of the forms. you upload attachments to existing contracts and this is saved into the model (Contract documents etc.. )

We shoudl support Form API, To be able to validate , show error messages as part of the forms, etc.

2020-10-28 18:55 UTC, Betrozov commented
> My Major comment would be that `Upload Collection `should be part of the Inputs. Upload components are usually used as part of the forms. e.g.: you upload attachments to existing contracts and this is saved into the model (Contract documents etc.. ), and soo on.
> 
> We shoudl support Form API, To be able to validate , show error messages as part of the forms, etc.

Hi @fkolar  :slightly_smiling_face: 

Regarding your comment, I have not seen in the docs any info about that...

While working on this component I have based on the following:
- https://sapui5.hana.ondemand.com/#/entity/sap.m.UploadCollection
- https://experience.sap.com/fiori-design-web/upload-collection/
- UC grid table - Ariba design

The listed sources did mention nothing about usage with Form.
`sapUI5` examples based on the instant upload strategy as well

2020-10-28 19:06 UTC, Betrozov commented
> I probably missed the review, otherwise I woudl make the change right there,
> we dont need Inputs like
> 
> uploadedBy, as this does not make sense on this Platform Level thsi is more Application specific behavior. Also I see in docs that there is binding called

`uploadedBy` - removed

> noDataText, -> Let;s sync it up with other components that we already have.
> In Table we use nodataMessage, some other place we have noDataLabel, etc..

The `UploadCollectionComponent` uses the same Input name `noDataText` as `BaseListItem` directive

2020-10-28 19:06 UTC, fkolar commented
I think its implicit. They dont need to mention this right? Let's try to think in what context is this Upload or UploadCollection is going to be used? Can you list usecases? 


I can see on the link you sent me that There is system to track tasks, Or Purchasing system, Contract Management and you are always uploading files within the context of some model. 

So you in real usecase you will have a page with different form fields and there will be also place to upload some attachemnts, and all this you should be able to link to one ENTITY (Domain Model instance) and then send all this togehter to the backend. 

So the rest of the field values from e.g. Contract will be automatically synced with Object, but in case of uploaded files application developer will have to do some addiional tasks.

2020-10-28 19:07 UTC, fkolar commented
We shoudl try to more understand how this component is going to be used in what realistic example.  Adding kevin to this discussion. To bad i mised the review on gitbook

2020-10-29 09:24 UTC, Betrozov commented
I just want to be on the same page with you.
So, we are talking about Ariba Design, Upload Collection use the Grid table as a container.
![upload-collection](https://user-images.githubusercontent.com/8318592/97549523-29834b00-19d9-11eb-8201-d8ad9e40c390.png)
FYI: @fkolar @KevinOkamoto

2020-10-29 15:02 UTC, KevinOkamoto commented
I'm unsure about @fkolar comment that the Upload Collection should be an input component within a form. My initial thoughts on the Upload Collection based on the UX mock-ups, is that this is a stand-alone complex component, similar to Approval Flow. Because the Upload Collection encapsulates all the CRUD interfaces in one component, I felt that it would need to interface with a specific file management service, not as part of a general domain model service. However I could be wrong.

Perhaps we should do more research, and ask PMs and UX designers under what context this component will be used. For now can we go with the current design, and if we need to change this component to be an Input component we can open a new PR for that?

2020-10-29 16:12 UTC, Betrozov commented
> If it handles its own CRUD operation then I am ok, but I did not see any CRUD operation in implemenation, it woudl be up to the developer to handle this.

Hi @fkolar 
plz look at the [UploadCollectionService](https://github.com/valor-software/fundamental-ngx/pull/95/files#diff-353c55c41e928d6403f0186911ca300e8748f253aa0667e0ebeb4ad301d19888R20)

2020-10-29 16:35 UTC, fkolar commented
> > If it handles its own CRUD operation then I am ok, but I did not see any CRUD operation in implemenation, it woudl be up to the developer to handle this.
> 
> Hi @fkolar
> plz look at the [UploadCollectionService](https://github.com/valor-software/fundamental-ngx/pull/95/files#diff-353c55c41e928d6403f0186911ca300e8748f253aa0667e0ebeb4ad301d19888R20)

Good. Even the idea of having dataSOURCE is that dataSOURCE uses DataProvider and data Provider knows how to handle the specific types of data. 

DataProviders is responsible for handling CRUD operation

2020-11-11 12:46 UTC, Betrozov commented
@fkolar please review one more time

2020-11-17 16:11 UTC, fkolar requested changes

2020-11-17 16:11 UTC, fkolar commented on libs/platform/src/lib/components/upload-collection/directives/upload-collection-dragndrop.directive.ts
> +export class UploadCollectionDragndropDirective {
Let's syncup the name with the directive selector. 

DragnDrop vs Dragndrop

2020-11-17 16:11 UTC, fkolar commented on apps/docs/src/app/platform/component-docs/upload-collection/examples/upload-collection-base-data-provider.ts
> +            uploadedBy: {
uploadedBy are these some default value.

2020-11-17 18:42 UTC, Betrozov commented on libs/platform/src/lib/components/upload-collection/directives/upload-collection-dragndrop.directive.ts
> +export class UploadCollectionDragndropDirective {
fixed

2020-11-17 18:43 UTC, Betrozov commented on apps/docs/src/app/platform/component-docs/upload-collection/examples/upload-collection-base-data-provider.ts
> +            uploadedBy: {
ignored

2020-11-18 09:02 UTC, fkolar approved these changes

2020-11-19 13:40 UTC, closed without merging